name: Test Artifact Storage

on:
  push:
    branches:
      - main

env:
    CYPRESS_MAILSLURP_API_KEY: ${{secrets.CYPRESS_MAILSLURP_API_KEY}}

jobs:
    report-creation:
        runs-on: ubuntu-latest

        steps:
        - name: Intialize NPM
          uses: actions/checkout@v4

        - name: Run Cypress
          uses: cypress-io/github-action@v6
          env:
            CYPRESS_MAILSLURP_API_KEY: ${{env.CYPRESS_MAILSLURP_API_KEY}} 
        - run: node reporter.js   
        
        
        - name: Trigger Cypress Tests
          uses: peter-evans/repository-dispatch@v2
          with:
            token: ${{ secrets.REPO_ACCESS_TOKEN }}
            repository: bhadmus/duplo-assessment
            event-type: trigger-tests
