image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

pipelines:
  default:
    - step:
        name: "Install and Run Test, Upload Result"
        script:
          # install dependencies
          - npm i
          # run cypress
          - npx cypress run --browser chrome
          - node reporter.js

        artifacts:
          - results/html/*.html